openapi: 3.0.1
info:
  title: PNP MantisBT Proxy API
  version: 1.1.0
servers:
  - url: https://0091-211-181-26-234.ngrok-free.app/api/rest/index.php

paths:
  /issues/{issue_id}:
    get:
      operationId: getIssueById
      summary: Get a specific issue by ID
      parameters:
        - name: issue_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single issue
          content:
            application/json:
              schema:
                type: object
                properties:
                  issues:
                    type: array
                    items:
                      $ref: '#/components/schemas/Issue'

components:
  schemas:
    Issue:
      type: object
      properties:
        id:
          type: integer
        summary:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        reporter:
          type: object
          properties:
            real_name:
              type: string
        status:
          type: object
          properties:
            name:
              type: string
        project:
          type: object
          properties:
            name:
              type: string
        category:
          type: object
          properties:
            name:
              type: string
