openapi: 3.0.1
info:
  title: PNP MantisBT Proxy API
  version: 1.0.0
servers:
  - url: https://0091-211-181-26-234.ngrok-free.app
paths:
  /issues/{issue_id}:
    get:
      operationId: getIssueById
      summary: Get issue by ID
      parameters:
        - in: path
          name: issue_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
components:
  schemas:
    Issue:
      type: object
      properties:
        id:
          type: integer
        summary:
          type: string
        description:
          type: string
        reporter:
          type: object
          properties:
            real_name:
              type: string
        created_at:
          type: string
        status:
          type: object
          properties:
            name:
              type: string
